{
  "name": "ict-trading-bot",
  "description": "ICT Trading Bot - OKX Real Data",
  "env": {
    "PYTHON_VERSION": "3.13.0"
  },
  "buildCommand": "pip install -r requirements.txt",
  "startCommand": "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"
}
